import { DarkTheme, DefaultTheme, type Theme } from 'expo-router';

export const THEME = {
  light: {
    background: 'hsl(0 0% 100%)',
    foreground: 'hsl(0 0% 9%)',
    card: 'hsl(0 0% 100%)',
    cardForeground: 'hsl(0 0% 9%)',
    popover: 'hsl(0 0% 100%)',
    popoverForeground: 'hsl(0 0% 9%)',
    primary: 'hsl(0 0% 9%)',
    primaryForeground: 'hsl(0 0% 100%)',
    brand: 'hsl(84 81% 44%)',
    brandForeground: 'hsl(0 0% 9%)',
    brandInk: 'hsl(84 85% 25%)',
    secondary: 'hsl(0 0% 96%)',
    secondaryForeground: 'hsl(0 0% 9%)',
    muted: 'hsl(0 0% 96%)',
    mutedForeground: 'hsl(0 0% 40%)',
    accent: 'hsl(0 0% 96%)',
    accentForeground: 'hsl(0 0% 9%)',
    destructive: 'hsl(0 72% 51%)',
    success: 'hsl(142 71% 45%)',
    warning: 'hsl(32 95% 44%)',
    border: 'hsl(0 0% 90%)',
    input: 'hsl(0 0% 90%)',
    ring: 'hsl(84 81% 44%)',
    radius: '0.5rem',
  },
  dark: {
    background: 'hsl(0 0% 6%)',
    foreground: 'hsl(0 0% 96%)',
    card: 'hsl(0 0% 10%)',
    cardForeground: 'hsl(0 0% 96%)',
    popover: 'hsl(0 0% 10%)',
    popoverForeground: 'hsl(0 0% 96%)',
    primary: 'hsl(0 0% 96%)',
    primaryForeground: 'hsl(0 0% 9%)',
    brand: 'hsl(84 81% 44%)',
    brandForeground: 'hsl(0 0% 9%)',
    brandInk: 'hsl(84 81% 44%)',
    secondary: 'hsl(0 0% 14%)',
    secondaryForeground: 'hsl(0 0% 96%)',
    muted: 'hsl(0 0% 14%)',
    mutedForeground: 'hsl(0 0% 64%)',
    accent: 'hsl(0 0% 14%)',
    accentForeground: 'hsl(0 0% 96%)',
    destructive: 'hsl(0 84% 60%)',
    success: 'hsl(142 71% 45%)',
    warning: 'hsl(38 92% 50%)',
    border: 'hsl(0 0% 18%)',
    input: 'hsl(0 0% 18%)',
    ring: 'hsl(84 81% 44%)',
    radius: '0.5rem',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.brand,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.brand,
      text: THEME.dark.foreground,
    },
  },
};
